"""SQLModel database models for HawkEye."""

from datetime import datetime
from typing import Optional
from uuid import uuid4

from sqlalchemy import Column, Index, String, Text, JSON, DateTime, Integer, ForeignKey, UniqueConstraint
from sqlmodel import Field, Relationship, SQLModel


class ApplicationSource(SQLModel, table=True):
    """Registered application source (API key holder)."""

    __tablename__ = "application_sources"

    id: Optional[int] = Field(default=None, primary_key=True)
    name: str = Field(max_length=100, index=True)
    api_key_hash: Optional[str] = Field(
        default=None, sa_column=Column(String(128), unique=True, index=True, nullable=True)
    )
    description: Optional[str] = Field(default=None, max_length=500)
    is_active: bool = Field(default=True)
    created_at: datetime = Field(default_factory=datetime.utcnow, sa_column=Column(DateTime, default=datetime.utcnow))
    updated_at: datetime = Field(
        default_factory=datetime.utcnow,
        sa_column=Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow),
    )

    # Relationships
    events: list["RawEvent"] = Relationship(back_populates="source")
    alerts: list["Alert"] = Relationship(back_populates="source")


class RawEvent(SQLModel, table=True):
    """Raw ingested event before normalization."""

    __tablename__ = "raw_events"

    id: Optional[int] = Field(default=None, primary_key=True)
    source_id: int = Field(foreign_key="application_sources.id", index=True)
    received_at: datetime = Field(
        default_factory=datetime.utcnow,
        sa_column=Column(DateTime, default=datetime.utcnow, index=True),
    )
    event_timestamp: datetime = Field(sa_column=Column(DateTime, index=True))
    payload: dict = Field(sa_column=Column(JSON))
    headers: Optional[dict] = Field(default=None, sa_column=Column(JSON))
    client_ip: Optional[str] = Field(default=None, max_length=45)
    user_agent: Optional[str] = Field(default=None, max_length=500)
    processed: bool = Field(default=False, index=True)

    # Relationships
    source: Optional[ApplicationSource] = Relationship(back_populates="events")
    normalized_event: Optional["NormalizedEvent"] = Relationship(back_populates="raw_event")


class NormalizedEvent(SQLModel, table=True):
    """Normalized event with common schema."""

    __tablename__ = "normalized_events"

    id: Optional[int] = Field(default=None, primary_key=True)
    raw_event_id: Optional[int] = Field(
        default=None, foreign_key="raw_events.id", unique=True, index=True
    )
    source_id: int = Field(foreign_key="application_sources.id", index=True)
    timestamp: datetime = Field(sa_column=Column(DateTime, index=True))

    # Categorization
    category: str = Field(max_length=50, index=True)
    event_type: str = Field(max_length=100, index=True)
    severity: str = Field(max_length=20, index=True)

    # Actor
    user_id: Optional[str] = Field(default=None, max_length=100, index=True)
    session_id: Optional[str] = Field(default=None, max_length=100, index=True)
    ip: Optional[str] = Field(default=None, max_length=45, index=True)
    user_agent: Optional[str] = Field(default=None, max_length=500)

    # Target
    route: Optional[str] = Field(default=None, max_length=500, index=True)
    method: Optional[str] = Field(default=None, max_length=10)
    status_code: Optional[int] = None

    # Context
    event_metadata: dict = Field(default_factory=dict, sa_column=Column(JSON))

    # MITRE ATT&CK
    mitre_tactic: Optional[str] = Field(default=None, max_length=100)
    mitre_technique: Optional[str] = Field(default=None, max_length=50)

    # Relationships
    source: Optional[ApplicationSource] = Relationship()
    raw_event: Optional[RawEvent] = Relationship(back_populates="normalized_event")
    alerts: list["Alert"] = Relationship(back_populates="event")

    __table_args__ = (
        Index("ix_normalized_event_lookup", "source_id", "timestamp"),
        Index("ix_normalized_event_actor", "ip", "user_id", "session_id"),
    )


class Alert(SQLModel, table=True):
    """Detection alert generated by a detector."""

    __tablename__ = "alerts"

    id: Optional[int] = Field(default=None, primary_key=True)
    source_id: int = Field(foreign_key="application_sources.id", index=True)
    event_id: int = Field(foreign_key="normalized_events.id", index=True)
    detection_type: str = Field(max_length=50, index=True)
    detector_name: str = Field(max_length=100)
    severity: str = Field(max_length=20, index=True)
    title: str = Field(max_length=200)
    description: str = Field(sa_column=Column(Text))
    evidence: dict = Field(default_factory=dict, sa_column=Column(JSON))
    confidence: float = Field(default=0.5)  # 0.0 - 1.0
    status: str = Field(default="new", max_length=20, index=True)
    created_at: datetime = Field(
        default_factory=datetime.utcnow,
        sa_column=Column(DateTime, default=datetime.utcnow, index=True),
    )
    updated_at: datetime = Field(
        default_factory=datetime.utcnow,
        sa_column=Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow),
    )

    # Relationships
    source: Optional[ApplicationSource] = Relationship(back_populates="alerts")
    event: Optional[NormalizedEvent] = Relationship(back_populates="alerts")
    incident_alerts: list["IncidentAlert"] = Relationship(back_populates="alert")


class Incident(SQLModel, table=True):
    """Correlated incident grouping related alerts."""

    __tablename__ = "incidents"

    id: Optional[int] = Field(default=None, primary_key=True)
    title: str = Field(max_length=200)
    description: str = Field(sa_column=Column(Text))
    severity: str = Field(max_length=20, index=True)
    status: str = Field(default="open", max_length=20, index=True)
    confidence: float = Field(default=0.5)  # 0.0 - 1.0

    # Affected entities
    affected_ips: list[str] = Field(default_factory=list, sa_column=Column(JSON))
    affected_users: list[str] = Field(default_factory=list, sa_column=Column(JSON))
    affected_routes: list[str] = Field(default_factory=list, sa_column=Column(JSON))

    # MITRE ATT&CK
    mitre_tactics: list[str] = Field(default_factory=list, sa_column=Column(JSON))
    mitre_techniques: list[str] = Field(default_factory=list, sa_column=Column(JSON))

    # Timeline
    first_event_at: datetime = Field(sa_column=Column(DateTime, index=True))
    last_event_at: datetime = Field(sa_column=Column(DateTime, index=True))
    created_at: datetime = Field(
        default_factory=datetime.utcnow,
        sa_column=Column(DateTime, default=datetime.utcnow, index=True),
    )
    updated_at: datetime = Field(
        default_factory=datetime.utcnow,
        sa_column=Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow),
    )
    closed_at: Optional[datetime] = Field(default=None, sa_column=Column(DateTime))

    # Relationships
    incident_alerts: list["IncidentAlert"] = Relationship(back_populates="incident")


class IncidentAlert(SQLModel, table=True):
    """Many-to-many link between incidents and alerts with ordering."""

    __tablename__ = "incident_alerts"

    id: Optional[int] = Field(default=None, primary_key=True)
    incident_id: int = Field(foreign_key="incidents.id", index=True)
    alert_id: int = Field(foreign_key="alerts.id", index=True)
    sequence: int = Field(default=0)  # Order in timeline
    created_at: datetime = Field(
        default_factory=datetime.utcnow,
        sa_column=Column(DateTime, default=datetime.utcnow),
    )

    # Relationships
    incident: Optional[Incident] = Relationship(back_populates="incident_alerts")
    alert: Optional[Alert] = Relationship(back_populates="incident_alerts")

    __table_args__ = (
        UniqueConstraint("incident_id", "alert_id", name="uq_incident_alert"),
    )


class ApiKey(SQLModel, table=True):
    """API keys for SDK authentication."""

    __tablename__ = "api_keys"

    id: Optional[int] = Field(default=None, primary_key=True)
    source_id: int = Field(foreign_key="application_sources.id", index=True)
    key_hash: str = Field(max_length=128, unique=True, index=True)
    name: str = Field(max_length=100)
    description: Optional[str] = Field(default=None, max_length=500)
    is_active: bool = Field(default=True)
    last_used_at: Optional[datetime] = Field(default=None, sa_column=Column(DateTime))
    expires_at: Optional[datetime] = Field(default=None, sa_column=Column(DateTime))
    created_at: datetime = Field(
        default_factory=datetime.utcnow,
        sa_column=Column(DateTime, default=datetime.utcnow),
    )

    # Relationships
    source: Optional[ApplicationSource] = Relationship()